# Generated by Django 3.1.1 on 2020-09-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
    ]
