# Generated by Django 3.1.1 on 2020-09-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_remove_answers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='group',
        ),
        migrations.DeleteModel(
            name='QuestionGroups',
        ),
    ]
