# Generated by Django 3.1.1 on 2020-09-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_auto_20200928_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='answers.questions'),
        ),
    ]
