# Generated by Django 3.1.1 on 2020-09-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200929_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='username'),
        ),
    ]
